# Generated by Django 4.1.5 on 2023-03-13 09:46

from django.db import migrations, models
import publik.utils


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_bookings_service_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='id',
            field=models.CharField(default=publik.utils.custom_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=publik.utils.custom_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.CharField(default=publik.utils.custom_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
