# Generated by Django 4.1.5 on 2023-02-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_asset_remove_post_content_remove_post_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
