# Generated by Django 4.1.5 on 2023-03-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_excerpt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
