# Generated by Django 4.1.5 on 2023-02-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
