# Generated by Django 4.1.5 on 2023-03-11 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import publik.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_products_notified_products_notify_products_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=publik.utils.custom_id, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ordered Items',
            },
        ),
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.CharField(default=publik.utils.custom_id, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products')),
            ],
            options={
                'verbose_name_plural': 'Ordered Item',
            },
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ordereditems'),
        ),
    ]
