# Generated by Django 4.1.5 on 2023-03-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_order_options_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='transaction_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
